### ISSUE TITLE
PowerShell Core support?

### ISSUE THREAD

**Issue by avishnyakov** [PoShLog/PoShLog#1]
Hi, thanks for this brilliant project. Example works well, all looks good and straightforward.

Wonder if there are plans to support PowerShell Core.
Could not get it running with PS Core 6.2, not sure why - didn't dig deeper.

```
Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by TomasBouda** [comment]
Hi, thanks for feedback 😊 
I would definitely like to add support for PowerShell Core. This is one of my favorite projects and I think it deserves some maintenance(it's been some time since I last commited here :disappointed:). Give me some time, I'll hopefully manage to add that support and I will notify you. Until then, have a nice day and happy coding :thumbsup:

**Comment by avishnyakov** [comment]
Noted, thanks @TomasBouda

**Comment by TomasBouda** [comment]
Hi @avishnyakov,

good news, I have version of PoShLog that works on PowerShell 7 :wink:
Once I'm done with polishing/testing/documenting I will release it. Hopefully till the end of next week :smirk:

If you are intrested you can download [preview](https://www.powershellgallery.com/packages/PoShLog/2.0.0-preview1) with:
```ps1
Install-Module -Name PoShLog -AllowPrerelease
```

and try quick example:
```ps1
Import-Module PoShLog

# Create and start new file and console logger - new short version
Start-Logger -FilePath 'C:\Data\my_awesome.log' -Console

Write-InfoLog 'Hurrray, my first log message!'

Close-Logger
```

or you can check the code in [dev](https://github.com/TomasBouda/PoShLog/tree/dev) branch.
If you have any questions or problems running the code, please let me know :relaxed:
Have a nice day and happy coding :rocket:

**Comment by TomasBouda** [comment]
Hi @avishnyakov,

if you are still intrested, I just published new version of PoShLog - [https://www.powershellgallery.com/packages/PoShLog/2.0.0](https://www.powershellgallery.com/packages/PoShLog/2.0.0)
Please let me know if it works for you. Otherwise I will close this issue after one week.

Happy coding 🚀

**Comment by avishnyakov** [comment]
@TomasBouda noted, thanks for sharing this.
