### ISSUE TITLE
Unable to load one or more of the requested types

### ISSUE THREAD

**Issue by devinnasar** [PoShLog/PoShLog#15]
Attempting to `Import-Module PoShLog` causes the following string of errors:

```

PS C:\Users\Administrator> import-module poshlog
Add-Type : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more
information.
At C:\Program Files\WindowsPowerShell\Modules\poshlog\2.1.1\functions\internal\Add-PackageTypes.ps1:9 char:4
+             Add-Type -Path $path
+             ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-Type], ReflectionTypeLoadException
    + FullyQualifiedErrorId : System.Reflection.ReflectionTypeLoadException,Microsoft.PowerShell.Commands.AddTypeComma
   nd

Add-Type : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more
information.
At C:\Program Files\WindowsPowerShell\Modules\poshlog\2.1.1\functions\internal\Add-PackageTypes.ps1:9 char:4
+             Add-Type -Path $path
+             ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-Type], ReflectionTypeLoadException
    + FullyQualifiedErrorId : System.Reflection.ReflectionTypeLoadException,Microsoft.PowerShell.Commands.AddTypeComma
   nd

Add-Type : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more
information.
At C:\Program Files\WindowsPowerShell\Modules\poshlog\2.1.1\functions\internal\Add-PackageTypes.ps1:9 char:4
+             Add-Type -Path $path
+             ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-Type], ReflectionTypeLoadException
    + FullyQualifiedErrorId : System.Reflection.ReflectionTypeLoadException,Microsoft.PowerShell.Commands.AddTypeComma
   nd

Add-Type : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more
information.
At C:\Program Files\WindowsPowerShell\Modules\poshlog\2.1.1\functions\internal\Add-PackageTypes.ps1:9 char:4
+             Add-Type -Path $path
+             ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-Type], ReflectionTypeLoadException
    + FullyQualifiedErrorId : System.Reflection.ReflectionTypeLoadException,Microsoft.PowerShell.Commands.AddTypeComma
   nd

Unable to find type [Serilog.Formatting.Display.MessageTemplateTextFormatter].
At C:\Program Files\WindowsPowerShell\Modules\poshlog\2.1.1\PoShLog.psm1:19 char:25
+ ... Formatter = [Serilog.Formatting.Display.MessageTemplateTextFormatter] ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Serilog.Formatt...teTextFormatter:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

```
Environment information:

```

PS C:\Users\Administrator> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.3866
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.3866
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
Any suggestions as to what might help here?

**Comment by TomasBouda** [comment]
Hi,
I'm sorry for the trouble, but thanks for reaching to me.
Can you please replace `C:\Program Files\WindowsPowerShell\Modules\poshlog\2.1.1\functions\internal\Add-PackageTypes.ps1` file contents with following code:

```ps1
function Add-PackageTypes {
	param(
		[Parameter(Mandatory = $true)]
		[string]$LibsDirectory
	)

	process {
		foreach ($path in (Get-ChildItem $LibsDirectory | Where-Object { $_.Name -like '*.dll' } | Select-Object -ExpandProperty FullName)) {
			try
			{
				Add-Type -Path $path
			}
			catch [System.Reflection.ReflectionTypeLoadException]
			{
				Write-Host $_.Exception.Message -ForegroundColor Yellow
				Write-Host $_.Exception.StackTrace -ForegroundColor DarkYellow

				if($null -ne $_.Exception.LoaderExceptions) { 
					foreach($loaderEx in $_.Exception.LoaderExceptions) { 
						Write-Host "LoaderException: $loaderEx" -ForegroundColor Cyan
					}
				}

				# throw 'Error occured while loading PoShLog libraries!'
			}
		}
	}
}
```

That should help us to see more information about what's wrong. Thank you 👍

**Comment by devinnasar** [comment]
Hello,

Sorry for the delay, I just came back from my weekend.

I'm unable to copy it at the moment, but the initial output of `Import-Module PoShLog` after adding your replacement included an instruction to set HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Fusion!EnableLog (DWORD) =1 in order to include further assembly binding information. I've done that.

Steps to reproduce:

1. Started new powershell session
2. `Import-Module PoShLog *> "C:\poshlog_issues.log"`
3. Errors are logged to file, which is attached. [poshlog_issues.log](https://github.com/PoShLog/PoShLog/files/5511524/poshlog_issues.log)

Some of my research over the weekend suggests that this might be related to too low a version of .NET framework installed. I believe that I've verified my .net version to be 4.7. 

```
PS C:\Users\Administrator> reg query "HKLM\SOFTWARE\Microsoft\Net Framework Setup\NDP\v4" /s

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Net Framework Setup\NDP\v4\Client
    CBS    REG_DWORD    0x1
    Install    REG_DWORD    0x1
    InstallPath    REG_SZ    C:\Windows\Microsoft.NET\Framework64\v4.0.30319\
    Release    REG_DWORD    0x70805
    Servicing    REG_DWORD    0x0
    TargetVersion    REG_SZ    4.0.0
    Version    REG_SZ    4.7.02053

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Net Framework Setup\NDP\v4\Client\1033
    CBS    REG_DWORD    0x1
    Install    REG_DWORD    0x1
    Release    REG_DWORD    0x70805
    Servicing    REG_DWORD    0x0
    TargetVersion    REG_SZ    4.0.0
    Version    REG_SZ    4.7.02053

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Net Framework Setup\NDP\v4\Full
    CBS    REG_DWORD    0x1
    Install    REG_DWORD    0x1
    InstallPath    REG_SZ    C:\Windows\Microsoft.NET\Framework64\v4.0.30319\
    Release    REG_DWORD    0x70805
    Servicing    REG_DWORD    0x0
    TargetVersion    REG_SZ    4.0.0
    Version    REG_SZ    4.7.02053

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Net Framework Setup\NDP\v4\Full\1033
    CBS    REG_DWORD    0x1
    Install    REG_DWORD    0x1
    Release    REG_DWORD    0x70805
    Servicing    REG_DWORD    0x0
    TargetVersion    REG_SZ    4.0.0
    Version    REG_SZ    4.7.02053
```

I unfortunately don't understand how to simply install another version onto the system. Most instructions seem to relate to using .NET in the context of a VSCode project, which is not what is happening. I am provisioning the server and using poshlog to create a log of of provisioning events.

I would appreciate any information you might be able to provide on why this is happening and what can be done to remedy it. Thanks!

**Comment by TomasBouda** [comment]
Hi,
thanks for the comprehensive information, I really appreciate it.
I was investigating few hours and I think I've find out the problem 👍 
I'll get some sleep and tomorrow morning will send you instructions how to hopefully fix it. See you in few hours 😄

**Comment by TomasBouda** [comment]
Hi,

thanks again for all info. I was browsing trough the fusion log you sent me and what immedieately caught my attention was message `Could not load file or assembly 'netstandard, Version=2.0.0.0`.
All C# libraries(see `C:\Program Files\WindowsPowerShell\Modules\poshlog\2.1.1\lib`) that PoShLog depend on are [.NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard) 2.0. .NET Standard Version 2.0 should be compatible with .NET Framework 4.6.1([see table](https://dotnet.microsoft.com/platform/dotnet-standard#versions)), but as documentation says - https://docs.microsoft.com/en-us/dotnet/standard/net-standard there are several issues and they recommend using .NET Framework 4.7.2 or higher. But that would be just too easy to say: 'Upgrade your .NET FW' :).

Instead, I was able to get machine with .NET 4.7.03190 and I tested PoShLog without problem there. So I read dozens of articles about .NET Standard, especialy this one https://medium.com/corrado-cavalli/hownetstandardwork-a6fdcd0adff8 describes how it works very nicely. Then I thought: *"from where does it resolve netstandard.dll?"*, well from [GAC](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/gac) and what happens if netstandard.dll is missing from GAC? I've immediately removed netstandard.dll from [GAC](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/gac) and ran `Import-Module PoShLog` form powershell, and voila, I've got the same error messages as you.

### Verify

Before we move to solution, please first verify that `netstandard.dll` is really missing from your GAC. I suppose you don't have a Visual Studio, so open `%windir%\Microsoft.NET\assembly` explorer, there are 3 folders(GAC_32, GAC_64, GAC_MSIL), netstandard should be under `GAC_MSIL`.
In case you have Visual Studio you can open Developer Command Prompt and run command: `gacutil –l` to list all assemblies in GAC.

### Solution

So now we know what is the problem(*well, I hope we know that*), but how do we fix it? Easiest way how to fix it is to install lastest .NET Framework Runtime(*4.8 at this moment*). You can find all runtimes here - [https://dotnet.microsoft.com/download](https://dotnet.microsoft.com/download). 
Just click `Download .NET Framework Runtime`. I've upgraded from 4.7 to 4.8 and netstandard.dll was automatically added to GAC.

### Dirty Solutions

 We have two options, either adding netstandard to [GAC](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/gac) or including it in PoShLog `\lib` folder and it's gonna load it automatically. 
 
 Only problem here is where to obtain correct netstandard library and unfortunatelly I didn't found answer to that. There is a nuget [NETStandard.Library](https://www.nuget.org/packages/NETStandard.Library), but it contains different dll as it's bundled with all System assemblies.
 
 ![image](https://user-images.githubusercontent.com/7009780/98669314-883db280-2351-11eb-9002-2e365d7efc2e.png)

I've included [netstandard.zip](https://github.com/PoShLog/PoShLog/files/5516667/netstandard.zip) from my GAC, so the answer is complete, but **keep in mind that using it not safe and you should use it as last possibility**.

#### Adding netstandard.dll to GAC

With PowerShell:

```ps1
[System.Reflection.Assembly]::Load("System.EnterpriseServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")
$publish = New-Object System.EnterpriseServices.Internal.Publish
$publish.GacInstall("C:\Users\Administrator\Downloads\netstandard.dll")
```

With gacutil:

```
gacutil -i netstandard.dll
```

#### Adding netstandard.dll to \lib

Copy `netstandard.dll` into `C:\Program Files\WindowsPowerShell\Modules\poshlog\2.1.1\lib`

### Summary

Please let me know if `netstandard.dll` was really missing and whether solutions above helped you. Good luck.

Tomas

**Comment by TomasBouda** [comment]
In case you have further questions, we can discuss on [![Discord](https://img.shields.io/discord/693754316305072199?color=orange&label=discord)](https://discord.gg/FVdVxuw) :relaxed:

**Comment by TomasBouda** [comment]
Hi @devinnasar, have it helped? Do you have any feedback on this?
If there is no response within 10 days I will close this issue.
