### ISSUE TITLE
SQL Synk Implementation

### ISSUE THREAD

**Issue by devgeek1968** [PoShLog/PoShLog#18]
Do you have a SQL Sink in PoshLog?

**Comment by TomasBouda** [comment]
Hi, no, not yet. But I have prepared draft of this sink months ago, so I might publish preview in couple of days.

**Comment by devgeek1968** [comment]
That would be great
Tks

**Comment by TomasBouda** [comment]
Hi,
here is prototype that you can test out - https://www.powershellgallery.com/packages/PoShLog.Sinks.MSSqlServer/1.0.0-preview1
Install it with: `Install-Module PoShLog.Sinks.MSSqlServer -AllowPrerelease`

and use it like this(**don't forget to change your ConnectionString**):

```ps1
Import-Module PoShLog
Import-Module PoShLog.Sinks.MSSqlServer

# Serilog's selflog just in case you get any errors
[Serilog.Debugging.SelfLog]::Enable({ param([string]$msg) Write-Warning $msg })

New-Logger | 
	Add-SinkMSSqlServer -ConnectionString 'Server=.;Database=dummy;Integrated Security=SSPI;' -TableName 'LogEvents' -AutoCreateSqlTable | 
	Add-SinkConsole | # You can ommit this sink
	Start-Logger

Write-InfoLog 'Test from {Where}' -PropertyValues 'PowerShell'

Close-Logger
```
The snippet above should create table `LogEvents` in your db and log single message into it.

![image](https://user-images.githubusercontent.com/7009780/117148864-f02bfd80-adb6-11eb-99b8-2f162b8f0972.png)

Try it and let me know how it works 👍 

**Note**
_I had trouble implementing it on both Windows PowerShell and PowerShell Core because there is bug in `Microsoft.Data.SqlClient.dll` and I think even in `System.Data.SqlClient.dll`, see this [issue](https://github.com/serilog/serilog-sinks-mssqlserver/issues/208). In the end I had to use different versions of `Serilog.Sinks.MSSqlServer` on each platform._

**Comment by TomasBouda** [comment]
hm, no feedback 😞, closing the issue

**Comment by fornax-a** [comment]
> Hi, here is prototype that you can test out - https://www.powershellgallery.com/packages/PoShLog.Sinks.MSSqlServer/1.0.0-preview1 Install it with: `Install-Module PoShLog.Sinks.MSSqlServer -AllowPrerelease`
> ....
> **Note** _I had trouble implementing it on both Windows PowerShell and PowerShell Core because there is bug in `Microsoft.Data.SqlClient.dll` and I think even in `System.Data.SqlClient.dll`, see this [issue](https://github.com/serilog/serilog-sinks-mssqlserver/issues/208). In the end I had to use different versions of `Serilog.Sinks.MSSqlServer` on each platform._

Many thanks for developing this event sink - Unfortunately I have run into a slight conflict between it and the Microsoft [Pnp-PowerShell](https://github.com/pnp/powershell) module, any assistance in resolving would be much appreciated. 

https://github.com/PoShLog/PoShLog.Sinks.MSSqlServer/issues/1
