### ISSUE TITLE
Console sink outputting to wrong streams

### ISSUE THREAD

**Issue by gitbute** [PoShLog/PoShLog#5]
Hi

Another problem in the console sink are streams. Right now it seems it doesnt use any Powershell streams at all. Test with *> $null which should hide every stream. The log messages still get displayed.

I think it would be nice to have the corresponding LogLevels also write to the correct powershell stream.

Best regards

**Comment by TomasBouda** [comment]
Hi,

this is hard one. As far as I know there is no easy/clean way how to do that. It's because PoShLog wraps C# library [Serilog.Sinks.Console](https://github.com/serilog/serilog-sinks-console)*(it uses uses [System.Console](https://docs.microsoft.com/cs-cz/dotnet/api/system.console?view=netcore-3.1) class)* and this library writes to `Success` *(1 or stdout)* and `Error` *(2 or stderr)* streams only *(actually by default it writes only to `Success` stream, but you can use [`-StandardErrorFromLevel`](https://github.com/PoShLog/PoShLog/wiki/Add-SinkConsole#-standarderrorfromlevel) on [`Add-SinkConsole`](https://github.com/PoShLog/PoShLog/wiki/Add-SinkConsole) cmdlet in order to write even in `Error` stream see example bellow)*.
Here is [thread](https://stackoverflow.com/q/50659334/4473849) on stackowerflow, discussing similar problem.

There is way how redirect these streams. Let's assume we have script `C:\test.ps1` with content below.

```ps1
Import-Module PoShLog

New-Logger |
	Add-SinkConsole -StandardErrorFromLevel Error | # This redirects all log messages with log level Error or Fatal to powershell Error stream
	Start-Logger

Write-InfoLog 'Hi'

try {
	throw 'Some error'
}
catch {
	Write-ErrorLog 'Error catched' -Exception $_.Exception
}

Close-Logger
```

Notice that we added parameter `-StandardErrorFromLevel Error` in order to wirte error(*and higher log levels*) log messages into powershell `Error` stream.
Then we can run **`powershell.exe C:\test.ps1 1>$null`**, which will ignore `Success` stream in this case showing only messages from `Error` stream:

![image](https://user-images.githubusercontent.com/7009780/84566147-522edf00-ad6f-11ea-97eb-608f272381c6.png)

I don't know what exactly you are trying to accomplish but I would recommend using cmdlets [`Set-MinimumLevel`](https://github.com/PoShLog/PoShLog/wiki/Set-MinimumLevel) or [`Set-LevelSwitch`](https://github.com/PoShLog/PoShLog/wiki/Set-LevelSwitch) to control which log levels are shown. Also keep in mind that every sink supports parameter `-RestrictedToMinimumLevel`, see [example 2.](https://github.com/PoShLog/PoShLog/wiki/Add-SinkConsole#example-2-restricting-log-levels).

I will keep this issue open and hopefully I or somebody else will find solution 🚀
Until then, happy coding and if you have any further questions feel free to ask ✋

**Comment by gitbute** [comment]
https://github.com/serilog/serilog/issues/1411 inda ties into the same idea and i think calls for a new serilog sink 'PSConsole'.
In my mind, this new sink should decide appropriate console loglevels by inspecting the automatic preference variables:
https://i.imgur.com/3b2owI7.png

**Comment by TomasBouda** [comment]
Hi,
added PowerShell sink as we discussed on discord. It's now available as [preview1](https://www.powershellgallery.com/packages/PoShLog/2.1.0-preview1), install it with:

```ps1
Install-Module -Name PoShLog -AllowPrerelease
```
or update previous version
```ps1
Update-Module PoShLog -AllowPrerelease
```

Then use it like this:

```ps1
Import-Module PoShLog

New-Logger |
	Set-MinimumLevel -Value Verbose -ToPreference |
	Add-EnrichWithErrorRecord |
	Add-SinkPowerShell -OutputTemplate '[{Timestamp:HH:mm:ss}] {Message:lj} {ErrorRecord}' |
	Start-Logger

# Test all log levels
Write-VerboseLog 'Test verbose message'
Write-DebugLog 'Test debug message'
Write-DebugLog 'Test debug message'
Write-InformationLog 'Test info message'
Write-InfoLog 'Test info message2'
Write-WarningLog 'Test warning message'
Write-ErrorLog 'Test error message'
Write-FatalLog 'Test fatal message'

# Test ErrorRecord
try {
    ConvertFrom-Json 'asd'
} catch {
    Write-ErrorLog 'Error occured' -ErrorRecord $_
}

Close-Logger
```

More information on new version is available here https://github.com/PoShLog/PoShLog/blob/master/releaseNotes/v2.1.0.md.

**Comment by gitbute** [comment]
'PS-Streams' enhancement implemented in the new preview versions :) Thanks for your work!
